// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyt8_A3pAuyE8Vf6fDMxFWuunl6XA5Afc',
    appId: '1:537831776333:web:2fca6ba44345d047397c04',
    messagingSenderId: '537831776333',
    projectId: 'stickiedb-35697',
    authDomain: 'stickiedb-35697.firebaseapp.com',
    storageBucket: 'stickiedb-35697.appspot.com',
    measurementId: 'G-9PHNCBP4B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr5Yq1mL0JM061begIZvq9QOhVPfSXMY0',
    appId: '1:537831776333:android:88e595372c287b9d397c04',
    messagingSenderId: '537831776333',
    projectId: 'stickiedb-35697',
    storageBucket: 'stickiedb-35697.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH15fWlPb9JagFd_G-zE6dFqQBB6jdRkk',
    appId: '1:537831776333:ios:8a2f85906d78784d397c04',
    messagingSenderId: '537831776333',
    projectId: 'stickiedb-35697',
    storageBucket: 'stickiedb-35697.appspot.com',
    iosBundleId: 'com.example.stickerMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH15fWlPb9JagFd_G-zE6dFqQBB6jdRkk',
    appId: '1:537831776333:ios:8a2f85906d78784d397c04',
    messagingSenderId: '537831776333',
    projectId: 'stickiedb-35697',
    storageBucket: 'stickiedb-35697.appspot.com',
    iosBundleId: 'com.example.stickerMap',
  );
}
